### ISSUE TITLE
New release maybe?

### ISSUE THREAD

**Issue by jgebal** [rsim/ruby-plsql#104]
Since last release there were quite few changes.
@javornikolov, you think it would be good idea to make a new release?

**Comment by javornikolov** [comment]
Absolutely!

**Comment by javornikolov** [comment]
@jgebal - I opened a PR for new release (version 0.6.0) - #107. You may take a look and check if it looks OK to you.

**Comment by jgebal** [comment]
@javornikolov This looks good. Thank you for updates to the history.
