### ISSUE TITLE
OUT parameter not added when calling procedure

### ISSUE THREAD

**Issue by serii833** [rsim/ruby-plsql#108]
considering pl/sql package like this

``` ruby
plsql.execute <<-SQL
    create or replace package test_package
    as
        procedure test1(a number := null, out_curs OUT sys_refCursor);
    end;

    create or replace package body test_package
    as
        procedure test1(a number := null, out_curs OUT sys_refCursor)
        as
            null;
        end;
    end;
SQL
```

when I make a call

``` ruby
plsql.test_package.test
```

It fails with "wrong number or types of arguments in call"
The reason is that generated sql doesn't contain OUT param. 
but if I do call like this

``` ruby
plsql.test_package.test(:a=>1)
plsql.test_package.test({})
```

it works.

as far as I understand in case of call 'plsql.test_package.test' arguments will be added only if they are all OUT. but they are not all OUT

``` ruby
Procedure_call.rb
197: if args.size < argument_count &&
                      (args.size...argument_count).all?{|i| arguments[argument_list[i]][:in_out] == 'OUT'}
```

**Comment by jgebal** [comment]
Confirmed, it actually doesn't work.
Confirmed it's this section of code that doesn't work.
The code for matching parameters by position looks a bit tricky.
If you pass in a Hash, the matching is done by parameter name.
We could say that if 0 parameters then... but this will not solve the whole issue but only this particular case.
@javornikolov any ideas?

**Comment by javornikolov** [comment]
Perhaps we should check for parameters which have default values. Maybe we already have that metadata, but I'm not sure right now - we need to check.
