### ISSUE TITLE
Performance issue with stored procs

### ISSUE THREAD

**Issue by scottolsen** [rsim/ruby-plsql#110]
We are using this gem to hit some stored procs for a client. We're digging in to some performance issues with the calls as they are taking 1.5 to 2 seconds. We finally got them to give us the raw sql for one of the calls and with the stored proc the average time is 1.85 seconds per call and when we run the raw sql it goes down to 1.07 on average. 

Also, their dba says it creates an extra table in their db on every call we make.
![ruby_oracle_connection_-_scott_entrepreneurialtechnologies_com_-_entrepreneurial_technologies_llc_mail](https://cloud.githubusercontent.com/assets/113754/16380571/7598663e-3c3d-11e6-98c4-f3d7a7600224.png)

Any help would be much appreciated!

**Comment by javornikolov** [comment]
Any hints about what the tests look like? What is the structure of that table which is being created on each call?
Which Ruby version are you using?

**Comment by scottolsen** [comment]
Hi @javornikolov,

We're using ruby 2.2.3. 

For the tests

```ruby
start_time = Time.now
foo = plsql.xxxx.xxxx.xxxx(bar) #or ActiveRecord::Base.connection.execute(sql)
end_time = Time.now
p "Total time: #{end_time - start_time}"
```

Waiting to hear back from the client on the table structure. Thanks!

**Comment by javornikolov** [comment]
One hypothesis so far is that there might be some trigger on database side performing some activities (possibly creating some table) upon connection. Or/and opening connections might be time consuming.

**Comment by javornikolov** [comment]
There is some overhead related to metadata queries issued by `ruby-plsql`. It's good to get more performance metrics about these database sessions (e.g. via tracing session and generate tkprof report).

**Comment by bpom** [comment]
as far as I know, ruby-plsql is using temp tables in some cases to support
types which are not supported by JDBC/OCI e.g. records, index-by tables.
Are your stored procs using such parameter types? usually they are deleted
as soon as the tests have finished.
Am 28.06.2016 18:01 schrieb "Yavor Nikolov" <notifications@github.com>:

**Comment by javornikolov** [comment]
Indeed - global temp tables are created in some cases: [procedure.rb#L209](https://github.com/rsim/ruby-plsql/blob/9f2f31f6f17967c5f204d87f8d1219b727422050/lib/plsql/procedure.rb#L209) - e.g. for records and table types defined inside a package.

The temp tables are dropped on connection [`logoff`](https://github.com/rsim/ruby-plsql/blob/9f2f31f6f17967c5f204d87f8d1219b727422050/lib/plsql/connection.rb#L74). @scottolsen - do you have an explicit `logoff` calls for your database connections?

Normally these tables should be small and quick to process. But it's good to confirm that.
As already I suggested - if you mange to profile your session calls you will be able see what takes most of the time. (One thing I've seen sometimes is degradation of queries to some of the `all_` Oracle dictionary views when the database has many synonyms or possibly large amount of other type of objects).

**Comment by scottolsen** [comment]
I am not explicity doing `logoff` so I'll try that to see if that gets rid of the extra tables. I know the client is currently running a nightly script to whack them all. I haven't gotten the table structure from them yet but they did send one of the actual stored procs and here is the [gist](https://gist.github.com/scottolsen/c396d530750bc4ba01466467d8f4129d) for that.

I'll give the session profiling a try to and see if that helps point me in the right direction. Thanks!

**Comment by javornikolov** [comment]
Returning tables of pl/sql records is [one of the cases relying on temp tables](https://github.com/rsim/ruby-plsql/blob/9f2f31f6f17967c5f204d87f8d1219b727422050/lib/plsql/procedure_call.rb#L441). Possibly you can compare if there is any difference between calling noop procedure returning table vs another noop simple one (varchar2 only arguments and results, maybe even outside a package).
