### ISSUE TITLE
Package variable data type VARCHAR2 (100) is not supported

### ISSUE THREAD

**Issue by shakerlxxv** [rsim/ruby-plsql#111]
There is a minor issue with the regex used to determine if a package variable is supported or not. VARCHAR2 is definitely supported. However, the space between the type and size is causing the variable to fall through a block in the Variable.metadata method.

``` ruby
    def metadata(type_string)
      case type_string
      when /^(VARCHAR2|CHAR|NVARCHAR2|NCHAR)(\((\d+)[\s\w]*\))?$/
        {:data_type => $1, :data_length => $3.to_i, :in_out => 'IN/OUT'}
```

I would suggest adding some support for whitespace between the type and the size, maybe:

``` ruby
      when /^(VARCHAR2|CHAR|NVARCHAR2|NCHAR)(\s*)?(\((\d+)[\s\w]*\))?$/
```

A simple work around in meantime is to remove the spaces between the type and size, assuming you have the access required to the underlying DB objects.

**Comment by javornikolov** [comment]
@shakerlxxv, thanks for reporting this issue and your proposal! Would you like to prepare request for it?

That also made me wondering about the case with space after `(`. E.g. can we end up with type_string `VARCHAR2( 100)` and what happens in such case.

**Comment by shakerlxxv** [comment]
I'd be happy to. It'll take me a few days to get to and will try work with the regular expression to accomodate the arbitrary spacing around the size values.
