### ISSUE TITLE
dynamically switch between connections?

### ISSUE THREAD

**Issue by dsusco** [rsim/ruby-plsql#115]
I have to connect to multiple databases dynamically in a Rails app in order to execute a stored procedure on each. It looks like this is supported by `PLSQL::Schema.find_or_new` and all I should have to do is:

```
plsql(:db1).my_proc(...)
plsql(:db2).my_proc(...)
plsql(:db3).my_proc(...)
```

I can't figure out how to create these connections and their aliases though. All three are in a yml file. Any suggestions?

**Comment by jgebal** [comment]
Hi @dsusco
Have a look at the example test case for using multiple connections:
https://github.com/jgebal/utplsql_vs_plsql_spec/blob/master/spec/message_api/send_and_receive_spec.rb
Here is the yml file used:
https://github.com/jgebal/utplsql_vs_plsql_spec/blob/master/spec/database.yml

Hope this helps.

Looking at your example you could do:
```ruby
[:db1,:db2,:db3].each do |db|
  plsql(db).my_proc(...)
end
```

**Comment by dsusco** [comment]
Thanks @jgebal,

Looking at [`spec_helper.rb`](https://github.com/jgebal/utplsql_vs_plsql_spec/blob/master/spec/spec_helper.rb) I created the following initializer so I can execute the procs:

    database_config = YAML.load_file("#{Rails.root}/config/shards.yml")['octopus'][Rails.env].recursively_symbolize_keys rescue nil

    database_config.each_pair do |db, params|
      plsql(db).connect!(params)
      plsql(db).connection.autocommit = true
    end

    at_exit do
      database_config.each_key do |db|
        plsql(db).logoff
      end
    end

Is the manual logoff strictly necessary?

Thanks for your help.

**Comment by javornikolov** [comment]
@dsusco, not so strictly necessary to explicitly call `logoff` but it helps to ensure your database sessions are closed when no longer needed. Open connections are consuming some resources on database side (memory, limit of open sessions, etc. - could be negligible in your case, I don't know).

There should be some garbage collection of un-closed connections at/after process exit http://stackoverflow.com/questions/2335862/ruby-oci8-not-logging-off-connection-consequences. Maybe via [timeout parameters](http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/timeout-parameters.md), I'm not sure. It's also possible to configure cleanup of idle connections on database server.

I consider a good practice to close database connections explicitly (similarly to closing files or network sockets). Also I prefer closing resources in the reverse order of their acquisition.
