### ISSUE TITLE
XMLTYPE in/out binds non-functional in 12C

### ISSUE THREAD

**Issue by AledLewis** [rsim/ruby-plsql#134]
I think the Oracle data-type field has changed from XMLTYPE -> OPAQUE/XMLTYPE. 

I've got a fix for the JDBC version of this library. It, however, does add a dependency to Oracle xdb/xmlparsev2 jars (which are even more annoying to get ahold of than the JDBC jar). 

I'm building off my fork for the moment. Is it something you want in your project (happy to refactor).

Here's the main commit. https://github.com/AledLewis/ruby-plsql/commit/14added895f27078d0e40e05a282be093c668088

**Comment by yahonda** [comment]
May be related to #114 I'd like to know if there is some document about this breaking changes done in Oracle Database 12c.

**Comment by AledLewis** [comment]
Still an issue.

**Comment by AledLewis** [comment]
@yahonda. I didn't look at a specification, I just inspected what the database was sending back.

**Comment by yahonda** [comment]
Thanks for the answer.
