### ISSUE TITLE
Release require for Ruby v2.4, v2.5 support with no warnings

### ISSUE THREAD

**Issue by jsmerritt** [rsim/ruby-plsql#158]
ruby-plsql v0.60 displays warnings in Ruby v2.4 and v2.5 due to deprecated Bignum and Fixnum The latest updates are required to use ruby-plsql with without warnings.

Release of lates changes is required ASAP. Our project cannot upgrade to Ruby v2.5.x until ruby-plsql does not produce these warnings. Any reference to Bignum and Fixnum must be removed. Integer type only for Ruby v2.4 and higher.

Requesting release ASAP.

**Comment by yahonda** [comment]
Thanks for the reminder

@javornikolov Do you have any plan to release the newer version of ruby-plsql? If no, I'm going to release 0.7.0 including these fixes.

https://github.com/rsim/ruby-plsql/compare/v0.6.0...master

Thanks.

**Comment by aboltart** [comment]
Any plans for 0.7.0 release?

**Comment by yahonda** [comment]
ruby-plsql 0.7.1 has been released https://rubygems.org/gems/ruby-plsql/versions/0.7.1 including https://github.com/rsim/ruby-plsql/commit/0098f71028638359947dc9b9235ba79b3860ca50 .

**Comment by yahonda** [comment]
Closing as ruby-plsql 0.7.1 has been released.
