### ISSUE TITLE
functions like max, min or sum on columns

### ISSUE THREAD

**Issue by schaary** [rsim/ruby-plsql#48]
Is it possible to compute functions like min, max, sum or avg on a column with ruby-plsql. It would be nice to have something like 

```
create table employee (
  name varchar2(255) 
  age integer
)
```

and then a call like 

```
plsql.employee.max 'age'
```

or 

```
plsql.employee.min 'age'
```

**Comment by jgebal** [comment]
Hi @schaary. Those features are not supported by ruby-plsql.
What you can do is use: `plsql.select 'select max(age) from employee'` you can also use: `plsql.emplyee.first(order_by: :age)[:age]` to get min
or `plsql.employee.first('order by age desc')[age]` to get max
