### ISSUE TITLE
not able to insert timestamp objects

### ISSUE THREAD

**Issue by schaary** [rsim/ruby-plsql#71]
Hi,

I use an  'Oracle Database 10g Express Edition Release 10.2.0.1.0 - Production'. Ruby v2.0.0 - v2.1.4 and ruby-plsql v0.5.2.

I try to insert a timestamp in a table but nothing happens. Like this:

    create table tmp_time_tbl (
      time_stamp timestamp;
    );

and then in ruby

    require 'ruby-plsql'
   
    # connect to oracle db

    ts = { time_stamp: Time.now }
   
    tmp_time_tbl.insert ts

It returns nil and nothing is inserted. When I insert a value by sqlplus, then I can fetch it:

    pry [v2.1.4]  >> ap plsql.tmp_time_tbl.first 
    {
        :time_stamp => 2014-11-09 08:36:40 +0100
    }
    => nil

ap is awesome_print. 

The problem still exists, when I try it by using pl/sql functions. If you are interested, I can post a example too.

**Comment by jgebal** [comment]
is this still open?

**Comment by javornikolov** [comment]
For me same example works OK. @schaary, are you still able to reproduce the issue?

**Comment by jgebal** [comment]
no response/ if it works for you I guess we can close this for now
