### ISSUE TITLE
JRuby INTEGER is not a Bignum it'a s Fixnum

### ISSUE THREAD

**Issue by jgebal** [rsim/ruby-plsql#85]
Discrepancy in type mapping.
On Ruby the INTEGER PLSQL datatype is converted to Bignum
(result of a function call returning INTEGER).
On JRuby however this is returned as a Fixnum.

Not sure if it's a bug or a feature, but it's an undocumented discrepancy.

**Comment by javornikolov** [comment]
This is a feature of JRuby: the range of values of Fixnum type is wider.
Closing this as it's an expected behavior.
