### ISSUE TITLE
Add a cheat sheet

### ISSUE THREAD

**Issue by jgebal** [rsim/ruby-plsql#89]
This is a follow up [from](https://github.com/rsim/ruby-plsql-spec/issues/21)
I've found a nice tool for generating cheat sheets - https://github.com/Kapeli/cheatset#readme
It would be good to have someone to collaborate on this.

**Comment by turntablez** [comment]
:+1: 
:+1: 
Look forward to this. 
Have you ever run any of the tests you have created in Jenkins/hudson?

**Comment by jgebal** [comment]
This is a bit off topic, please contact me via linkedIn or through my [blog](http://www.oraclethoughts.com).
I don't want to spam this thread.

**Comment by turntablez** [comment]
No problems I see the first thing on your blog is what I have asked about anyway!
Thank you :+1:

**Comment by jgebal** [comment]
@javornikolov @rsim I wonder, if it's valuable to add the [cheat sheet](http://www.oraclethoughts.com/testing/ruby-plsql-cheatsheet/) to the project directly?

**Comment by javornikolov** [comment]
Yes, why not. I think it's a good idea :+1:

**Comment by jgebal** [comment]
You thing it's better to put the pdf into project or just a link into the cheat sheet on [cheatography](http://www.cheatography.com/jgebal/cheat-sheets/ruby-plsql-cheat-sheet/)

**Comment by jgebal** [comment]
Can be closed.

**Comment by javornikolov** [comment]
Resolved by #101
