### ISSUE TITLE
RSpec 3.4 and objects

### ISSUE THREAD

**Issue by jgebal** [rsim/ruby-plsql#97]
With RSpec 3.4 the assertions on objects doesn't work for me any more.
The following example fails:

```
    expected = { type_code: plsql.dbms_types.typecode_bdouble, type_name: 'BINARY_DOUBLE', data_value: 12345 }
    result = plsql.any_data_bdouble(12345)
    expect( result ).to eq( expected )
```

with exception

```
ArgumentError: No PL/SQL procedure 'TO_ARY' found for type 'ANY_DATA_BDOUBLE' object
./spec/any_data_scalar/create_spec.rb:6:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

I did some digging around and I found a reason.
The `method_missing` should come in pair with `respond_to?` implementation.
http://stackoverflow.com/questions/291132/method-missing-gotchas-in-ruby

The workaround for this seems to be adding:

```
  class ObjectInstance < Hash #:nodoc:
...
    def respond_to?(method, include_private = false)
      super(method, include_private)
    end
```

so that RSpec can inspect object for methods prior to invoking them.

**Comment by jgebal** [comment]
I think this is related to object containing datatype unsupported by ruby-plsql in it - BINARY_DOUBLE.

**Comment by javornikolov** [comment]
Does the same issue reproduce with RSpec < 3.4?
